services:
  proxy:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_proxy
    ports:
      - "18452:80"
    build: 
      context: ./proxy
      additional_contexts:
        - static=./static
  broker:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_broker
    build:
      context: ./broker
  api-gateway:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_api_gateway
    build:
      context: ./api_gateway
    env_file:
      - ./default.env
  tour-operator:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_tour_operator
    build:
        context: ./tour_operator
    env_file:
      - ./default.env
  trip-reservations:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_trip_reservations
    build:
        context: ./trip_reservations
    env_file:
      - ./default.env
  price-calculator:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_price_calculator
    build:
      context: ./price_calculator
  auth:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_auth
    build:
      context: ./auth
    env_file:
      - ./default.env
  transports:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_transports
    build:
        context: ./transports
    env_file:
      - ./default.env
  tour-offers:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_tour_offers
    build:
        context: ./tour_offers
    env_file:
      - ./default.env
  trip-status:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_status
    build:
        context: ./status
    env_file:
      - ./default.env
