services:
  proxy:
    image: nginx
    ports:
      - "8080:80"
    build: 
      context: ./proxy
      additional_contexts:
        - static=./static
    depends_on:
      - dummy
    develop: # To be removed before deployment
      watch:
        - path: ./static/html
          action: sync
          target: /data/www
  dummy: # To be replaced by api gateway
    image: nginx
