services:
  proxy:
    develop:
      watch:
        - path: ./static/html
          action: sync
          target: /data/www
    depends_on:
      - api-gateway
  api-gateway:
    develop:
      watch:
        - path: ./api_gateway
          action: rebuild
  db-sql:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_db_sql
    ports:
      - "15432:5432"
    build:
      context: ./db_sql
  db-mongo:
    image: ghcr.io/yetanotherspieskowcy/rsww_184529_db_mongo
    ports:
      - "17017:27017"
    build:
      context: ./db_mongo
  auth:
    env_file:
      - ./dev.env
  trip-reservations:
    env_file:
      - ./dev.env
  transports:
    env_file:
      - ./dev.env
  tour-offers:
    env_file:
      - ./dev.env
  trip-status:
    env_file:
      - ./dev.env
