services:
  proxy:
    image: 10.40.71.55:5000/rsww_184529_proxy
    ports:
      - "8080:80"
    build: 
      context: ./proxy
      additional_contexts:
        - static=./static
  broker:
    image: 10.40.71.55:5000/rsww_184529_broker
    build:
      context: ./broker
  api-gateway:
    image: 10.40.71.55:5000/rsww_184529_api_gateway
    build:
      context: ./api_gateway
    env_file:
      - ./default.env
  tour-operator:
    image: 10.40.71.55:5000/rsww_184529_tour_operator
    build:
        context: ./tour_operator
  price-calculator:
    image: 10.40.71.55:5000/rsww_184529_price_calculator
    build:
      context: ./price_calculator
