name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
permissions: read-all
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_PYLINT: false
          DEFAULT_BRANCH: origin/main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}