name: Selenium tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
permissions: read-all
jobs:
  build:
    name: Selenium tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_CLONE_TOKEN }}
          submodules: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r functional_tests/requirements.txt
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run docker
        run: docker compose --profile local up --build -d
      - name: Fill DB with sample data
        run: |
          # this is a rare case where lack of quoting is actually done on purpose
          # shellcheck disable=SC2046
          export $(cat default.env dev.env | xargs)
          db_scripts/fill_with_sample_data.sh
      - name: Run functional tests
        run: python -m pytest functional_tests/
      - name: Shut down docker
        run: docker compose down
